# Generated by Django 4.2.6 on 2023-12-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_processing', '0002_teacher_teacher_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='section',
            name='number_of_constructive_comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='number_of_positive_comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='year',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(max_length=1000)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDF_processing.section')),
            ],
        ),
    ]
