# Generated by Django 4.2.6 on 2023-12-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_processing', '0004_comment_category_alter_comment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='number_of_positive_comments_ass',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='number_of_positive_comments_classenv',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='number_of_positive_comments_content_org',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='number_of_positive_comments_learning_mat',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
