# Generated by Django 4.2.6 on 2024-03-21 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_processing', '0005_section_number_of_positive_comments_ass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respon', models.CharField(default='', max_length=1000)),
                ('category', models.CharField(default='', max_length=1000)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDF_processing.section')),
            ],
        ),
    ]
